### ISSUE TITLE
1.1版本客户端和服务端的配置文件完整版本的谁有，发我一份吧，

### ISSUE THREAD

**Issue by afdnlw** [v2ray/v2ray.github.io#1]
之前的版本还好弄 ，最近关注的少了，不清楚怎么配置 了，后来好像加了很多东西。谁有请发一份到afdnlw@gmail.com，按照之前那种配置文件，不成功了，，，

**Comment by v2ray** [comment]
每份安装包都带了最新的配置文件：https://github.com/v2ray/v2ray-core/releases

如果你遇到任何错误信息，请把错误信息写在 issue 中，方便判断原因。

https://github.com/v2ray/v2ray.github.io/wiki/Issue-%E6%8C%87%E5%BC%95
