### ISSUE TITLE
1.3win客户端与脚本安装服务器端"alterId"配合有问题

### ISSUE THREAD

**Issue by frankpen** [v2ray/v2ray.github.io#3]
今天第一次在debian上用脚本安装，始终ID认证出错，后来排故发现是win客户端"alterId"不能删除必须设为0. debian服务端config.json里"alterId"参数必须删除，否则无法运行。
     但是使用你们提供的服务器"alterId"默认是1024可以正常运行。

**Comment by nickyhzp** [comment]
@frankpen 刚才我也遇到了，认证错误。看了说明，“alterId”必须把服务器端与客户端设置一样才可以，设置一样之后，认证通过，可以上网

**Comment by frankpen** [comment]
解决了！服务器端“level”字串必须删除，保留默认的“level”：1的话认证始终无法通过。

**Comment by v2ray** [comment]
alterId 和 level 没有关系。alterId 必须在服务器端和客户端的值一样。@frankpen 你可以试一下在 alterId 一致的情况下把 level 加回去。

**Comment by frankpen** [comment]
试过了，有 level 认证就会失败。level 字段和 alterId在配置里先后顺序没有要求吧？
 
目前我多用户配置，分别设了2个ID，第一个ID 只写alterId，第二个ID 只写 level ，可以正常运行。

后来第一个ID alterid后写level，第二个ID level 后写alterid，服务器端无法运行。

**Comment by v2ray** [comment]
顺序没有关系

“服务器端无法运行”是什么意思，进程退出？如果是这样的话，说明你的配置文件格式错误，多数情况是多写了一个逗号

**Comment by frankpen** [comment]
是我语法错了，没有加逗号导致的。
