### ISSUE TITLE
在IE 11设置了127.0.0.1 1080，然后打开v2ray.exe 防火墙允许，无法上网，Unknow protocol version 67

### ISSUE THREAD

**Issue by ntgeralt** [v2ray/v2ray.github.io#4]
直接下载允许v2ray.exe 64位版，看解释说里面自带公共服务器，IE 11设置好127.0.0.1:1080，v2ray.exe出现Unknow protocol version 67.是什么意思？

ps：网上搜ie使用sock5代理才发现很多步骤，和goagent的大有不同，ie sock被翻译成‘套接字’..好像掉坑了。
最后ie和chrome SwitchyOmega能用了（刚设置好直接访问google没反应，等了半分钟才能访问上），法国节点；正常使用时v2ray.exe还有些error刷出来，fail to read vmess response bababa  太长又不给复制..

**Comment by v2ray** [comment]
Please re-open this issue at [v2ray-core](https://github.com/v2ray/v2ray-core/issues) if necessary.
